### ISSUE TITLE
Meet The Makers | Nov 23rd | Mental Health as a Public Good

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1008]
Another edition is here: Mental Health as a Public Good

It will take a place in our discord community channel November 23rd instead of regular AMA.

Projects that confirmed for NOV 23rd:

- https://giveth.io/project/we-the-medicine-healing-through-warriors-soul and David Price
- https://giveth.io/project/gravity-dao Juan and Bianca
- https://giveth.io/project/happydao-l-mental-healthcare-for-all Alvaro

There is potentially still one open spot but for the time sake we are moving forward with three projects.

Updated event plan is here:
https://docs.google.com/document/d/11pAUmN18p9_xm-DSG2dNKPApBFph0V5QNv90B5D-2p4/edit?usp=sharing

Task manager:

- [x] PostMTM review call and planning
- [x] Select and invite project owners - guests
- [x] Update Giveth calendar
- [x] Send an autopilot email invite for participants
- [x] Communications and shilling (start executing by 11.11 the latest)
- [x] Finalize content and session flow before the event starts
- [x] Post event shilling (share the recording
- [ ] Post event evaluation call + planning
