### ISSUE TITLE
Meet The Makers Feb 8th | Inclusion

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1153]
Returning back to the quarterly cycle. Coordination sync up notes: 
https://docs.google.com/document/d/1kOx8D7_yVj0nK-zmjUwGMG9rvcrQyAc3dR71T5hEhmA/edit?usp=sharing

The next edition will take place Feb 8th in the regular AMA slot.
Host: Dani (Nikola & Almond support)
Topic: Inclusion
Tech support: Ashley (&Franco)

- [x] Coordination team sync-up call (set up time, topic, nominate projects)
- [x] Invite projects
- [ ] Outline Event flow with Dani
- [x] Create banner designs
- [x] Create Comms plan
- [x] Consult streaming platforms (streamyard?)

**Comment by franculio** [comment]
@NikolaCreatrix in regards of the streaming platform I use OBS which transmits what's going on Discord into Youtube. Were you thinking in also streaming into other platforms? Like Facebook or Twitter? I know that OBS can also transmit to those ones as well, I could take a look into it. But Streamyard seems to be a paid service tool, did you have in mind specifically this one for some reason?

**Comment by WhyldWanderer** [comment]
We already have a Streamyard account... its what we use for the GM podcast. 
I think OBS only lets you stream to one platform at a time... Streamyard lets us stream to 3 at once.

**Comment by NikolaCreatrix** [comment]
I like what we discussed in our check-in today, so just making a few notes here:

The event will happen on Streamyard - it's a great solution for getting out of the discord because you only need to click one link to enter the meet space. 

Ashley offered to screenshare on Discord.

Question: Does Streamyard allow participants to share their screens if they have a presentation to showcase? @oyealmond do you know?

We will stream it on these platforms and each will need someone monitoring activity and questions:
YouTube
Twitter
LinkedIn

**Comment by oyealmond** [comment]
Banner Ready @NikolaCreatrix 

<img width="1024" alt="Meet_Inclusivity" src="https://user-images.githubusercontent.com/110692280/214949742-17ba2d66-21a2-4719-bb17-5b65fd902488.png">
