### ISSUE TITLE
Meet The Makers | Spanish edition| Earth Day April 19th

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1228]
Based on our last retrospective session we have picked the next MTM date. Meeting notes can be viewed here:
https://docs.google.com/document/d/1GvgegKOISFtPcXlSEO7ZFB6n9e6RbQlIn_JpKESqc2U/edit?usp=sharing

**Next Edition:**

**Special edition - Earth Day in Spanish**

Specifically to support Spanish-speaking projects.

The Date: we have picked April 22nd, 2023 Earth day - note this is Saturday...so we should adjust @oyealmond and @WhyldWanderer either for 19th or 26th wyt?

Tasks:

- [x]  Finalize the date
- [x]  Reach out to nominated projects posted in the MTM planning channel
- [x]  Invite Host and co-host - Cotabe and Humberto
- [x]  Create email invites
- [x]  Create comms plan + designs
- [x]  Create event outline and script (implement notes from the meeting notes above
- [ ]  Retrospective session + planning.

**Comment by WhyldWanderer** [comment]
@oyealmond Is there already a graphic for this edition of MTM? We can add it to the Whats up on Giveth section of the homepage 🚀

**Comment by oyealmond** [comment]
wdyt @WhyldWanderer? 

<img width="1024" alt="Earth Day" src="https://user-images.githubusercontent.com/110692280/229258119-9e87ed30-7d07-4e00-9613-77475bdeec62.png">
