### ISSUE TITLE
Meet The Makers August 2nd 

### ISSUE THREAD

**Issue by NikolaCreatrix** [Giveth/giveth-planning#1466]
This is an epic for another Meet The Makers event. 
MTM has now its own notion page. https://www.notion.so/giveth/Meet-The-Makers-ff1b12feab904013b8ed5ae2c0a97e9d

This time the upgrade is:

- we host max 10 project owners within 60 minutes on Streamyard (5 minutes per pitch)
- we invite newly verified projects and stop planning for themes
- using MeetTheMakers # newly on the homepage and also just going into featuring newly verified projects
- storytelling & interview by @suga to come (2-3 projects per month?)

Next session - August 2nd, 9 am CostaRica time
Platform - streamed across all platforms using StreamYard.

Todos:

- [x] Project outreach @NikolaCreatrix 
- [x] Calendar event (Google & Discord)
- [x] Comms plan - @oyealmond (All platforms + discord)

cc @WhyldWanderer
