### ISSUE TITLE
Gitcoin GG19 prep (Nov 15-29)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1632]
![Screenshot_20231021_090821_X.jpg](https://github.com/Giveth/giveth-planning/assets/75490971/4303b91a-e4fe-40f8-98f0-ad5df2d75991)

We should:
- [x] update project description
- [x] prepare announcement tweet thread
- [ ] prepare follow up tweets
- [ ] look for Twitter spaces & assign joiners
- [ ] prepare announcement email
- [ ] prepare x days left email

We could make this an epic w subissues, just wanted to get it up.

cc @oyealmond

**Comment by oyealmond** [comment]
This is an epic now. Thanks @laurenluz

**Comment by Cotabe** [comment]
FYI: @laurenluz @oyealmond 

@brichis will be taking on all the fundraising support to Giveth. In the next month will be doing a smooth transition & we might work on some things together, but she will be leading this effort from the fundraising side.

@laurenluz I also suggest moving Giveth to the Web3 Community and Education category.

**Comment by laurenluz** [comment]
@Cotabe - agree! will more to web3 community this round. I talked to @brichis already and will take this and onboard here
