### ISSUE TITLE
Change-maker social media campaign

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#173]
We have planned to launch the social media change-maker campaign beginning April 14 and expect it to last about 4 weeks with the intention of gathering stories, onboarding new projects and featuring story/project submissions across our social media platforms.  
OG launch post is here - https://docs.google.com/document/d/197oPHlxjFNhd3Jfhsb0oXViYsAa_0-n9qubbrg38Eh4/edit
## In Preparation for launch we must: 

- [x] Finish QA on change-maker launch post 

- [x] Draft Tweets for launch 

- [x] Format Medium post for launch

- [x] Format Reddit post for launch

- [x] Format/Draft post for Bloom Network 

- [x] MORE MEMES

## For Launch we must:

- [x] Post to Medium

- [x] Twitter Tweets

- [x] Post to r/Giveth and relevant subreddits

- [x] Post to Bloom Network

## Post-launch for the next 4 weeks some recurring tasks: 

 - Recurring Tweets for campaign and new projects onboarded

 - Recurring reddit posts

- Recurring Bloom Network posts

 - Collect and assess stories submitted

 - Write content for stories, do QA and publish

 - **never enough memes**

**Comment by ForestSoleil** [comment]
Agenda for comms jam session today:

- What's the plan from Bloom Network to support the social impact campaign?
>>> Someone from comms team to post on Bloom Network discord server to announce and promote campaign and connect with new projects to add to Giveth.
>>> Create a byline/blurb around Giveth social impact campaign. 
>>> Bloom Network blog is good for more people learning that Giveth exists. When we have stories/submissions, we can share these with Bloom for sharing or Magenta can post pointing to our Giveth Medium round up articles sharing the featured projects. 

- Review checklist for preparation we can go through on the epic Mitch created on github.

- Quick discussion on how we can collect info as submissions are made
>>> They are required to create a project on giveth.io. In order to have a profile, they need to enter an email. 
>>> We will also have their twitter or reddit social handle for communication
>>> They are required to enter their project's giveth.io link when sharing on social media with our campaign hashtag.
>>> Add projects to Project Outreach spreadsheet so we can track who we have already promoted and who needs to be scheduled. Name of project/cause, link to project, contact info, submission date, status of promo, notes.

- Decide on how exactly we plan to feature projects (so we can include that in the launch post)
>>> Share and link to their project in weekly Medium article round up. Share link to Medium article on Twitter and Reddit.

- Create a distribution schedule for sharing/shilling and take respective ownership so it's not just one person in all the channels

- Drafting tweets

- Make awesome memes about the social impact campaign

**Comment by ForestSoleil** [comment]
Link to Google doc I created with twitter thread of 5 tweets outlining the details of the campaign to be scheduled for tomorrow, Friday April 16th. 
https://docs.google.com/document/d/1kVPw9X71ALhkTjQBJmrwK3ZJU-mxXdwOJplPXHuwlKg/edit?usp=sharing

@laurenluz please schedule this post for tomorrow.
@magentaceiba please share Twitter login credentials with Lauren as soon as possible.

**Comment by magentaceiba** [comment]
Ooh nyce thread!! I asked for the login credentials as I can't find them anywhere, will share asap

**Comment by laurenluz** [comment]
yeah great thread @ForestSoleil  - thanks so much! Just wondering if we can change "gaia speed"? I don't think it resonates so much with our current audience?

**Comment by laurenluz** [comment]
@magentaceiba I still don't have access to the twitter

**Comment by magentaceiba** [comment]
Hi @laurenluz I asked for the password but haven't gotten it yet, I can't find it anywhere in my chats or pwd manager. @Danibelle do you know who would have it, or if I can reset it?

**Comment by magentaceiba** [comment]
Hi @laurenluz I asked for the password but haven't gotten it yet, I can't find it anywhere in my chats or pwd manager. @Danibelle do you know who would have it, or if I can reset it?

**Comment by Danibelle** [comment]
Oh I have Twitter and will share it wirh @laurenluz

**Comment by divine-comedian** [comment]
Extended until GIV token launch! yay
