### ISSUE TITLE
Wiki to Docs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#185]
Each section below will be assigned to an individual (or crossed out, if no longer relevant). That person will be responsible to aggregating correct information and copy editing their respective section, effectively preparing the info to be transferred into the docs.

Info from: https://wiki.giveth.io/

- [x] Welcome @laurenluz 
- [x] Giveth Community (DAC) @laurenluz 
     - [x] About the Giveth DAC @laurenluz 
     - [x] Calendar & Events @laurenluz 
     - [x] Team Organization @laurenluz 
     - [x] Mission @laurenluz 
     - [x] Goals @laurenluz 
     - [x] Finances - to be redone to reflect governance spreadsheet @Danibelle 
     - [x] History @geleeroyale 
     - [ ] Documentation
          - [ ] Adopted Policies
          - [ ] Meeting Notes
- [x] Dapp Development
     - [x] Intro to the Giveth DApp (explain why there are 2 Dapps) @divine-comedian https://docs.beta.giveth.io/
     - [x] Product Definition @divine-comedian 
     - [x] Roadmap (giveth.io has this in the notion... @MoeNick is working on this for TRACE)
     - [x] Documentation & Tutorials @divine-comedian (TRACE & giveth.io)
          - [x] How to make Milestones  @divine-comedian 
          - [x] Future @divine-comedian 
          - [x] Exchange Rate @divine-comedian 
          - [x] Dev Process & QA @divine-comedian 
          - [x] Smart Contracts Roadmap @divine-comedian 
          - [x] Deployments @divine-comedian 
          - [x] Technical Challenges @divine-comedian 
- [x] Governance @ForestSoleil 
     - [x] Intro to Giveth Governance @ForestSoleil 
     - [x] Job openings @ForestSoleil 
     - [x] Documentation & Tutorials @ForestSoleil 
          - [x] Contributors Guide @ForestSoleil 
          - [x] Governance of Meetings (are we moving to Sociocracy-ish?) --> add to governance discussion?
          - [x] Code of Conduct @ForestSoleil 
          - [x] Advice Process @ForestSoleil 
          - [x] Conflict Resolution (Lorelai's role at Giveth) @ForestSoleil 
          - [x] Tools for DACs @ForestSoleil 
          - [x] Recording Meetings Guide @laurenluz 
     - [ ] Unicorn DAC (ignore for now)
          - [ ] Unicorn DAC Intro
          - [ ] Unicorn Onboarding
          - [ ] Get Funding
          - [ ] Roles Process
          - [ ] Known Unicorns
- [x] Communications @WhyldWanderer 
     - [x] Intro to Giveth Communications @WhyldWanderer 
     - [x] Documentation & Tutorials
          - [x] Brand Identity Guide @markoprljic 
          - [x] Use of Riot Chat --> make this *use of discord* (manual and best practices - don't include internal channels) @WhyldWanderer 
- [ ] Social Coding (do not edit, for now)
     - [ ] Intro to Giveth Social Coding

We will be using https://hackmd.io/?nav=overview for all documents.

**Comment by laurenluz** [comment]
@WhyldWanderer you seem to have it down now ;) in the call, we checked the boxes for the sections that we deemed "appropriate to keep/look at". if your name is next to a section that is "checked" you can make an issue for that section and add the issue to this epic

**Comment by MoeNick** [comment]
@laurenluz where can i have the giveth.io roadmap on notion. it gives me some clue i think.

**Comment by laurenluz** [comment]
@MoeNick looks like here: https://www.notion.so/giveth/Roadmap-5a154f91bf9a417ea31b2edbc925201a

but I don't think it's been looked at/updated in quite some time
