### ISSUE TITLE
2021 Q3 Milestone Planning

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/giveth-planning#232]
- Forest guiding the team through creating pragmatic targets and goals that we want to achieve as a communications circle on a quarterly basis, giving us something to look ahead to and work toward to kick off Q3 2021 July-September.
- Need to understand road maps, quarterly planning, goals from other projects & circles, and high level Giveth to give us a clear vision as a comms team and a basis to align with. 
- Answering the question: What do we want to reach at the end of Q3 of this year?

**Comment by ForestSoleil** [comment]
Notes from initial discussion on Monday June 7th: https://www.notion.so/giveth/Monday-June-7th-2021-Quarterly-Milestone-Planning-395f4d4b2fdc4d18801d63b3792a953d

Process we are in the process of going through: 

- [ ] #1 Let's brainstorm all of our opinions - there are no wrong answers! 
- [ ] #2 Consider all of the opinions together, even the hidden voices that are not included in the meeting. Need to get to know more about them.
- [ ] #3 Discuss which ones most align and feel attainable. The goal shouldn’t be too easy or too hard. 
- [ ] #4 Can you see any blocker or problem that might be risky for our goal?
- [ ] #5 Consent to our shared goals
- [ ] #6 What are the milestones we need to set to reach this goal or each of these goals?
- [ ] #7 How do we want to organize? Do we want to run sprints? Or keep things more casual?

**Comment by WhyldWanderer** [comment]
@ForestSoleil is this still in progress?

**Comment by ForestSoleil** [comment]
Thanks for the reminder to close this Ashley! 
The Q3 planning process is complete. 

These are the goals we decided upon:
- ✅ Launching strategic comms messaging around Giveth TRACE
- ✅ Completing Docs Migration
- 🤼 Improving Cross Circle Communications: Mission Vision Values Alignment & Announcement
- 🤼 Launching strategic comms messaging around GIV Token Economy

In process on the last two but have made significant progress! We have through the end of September to complete.
