### ISSUE TITLE
Publicly release TRACE - content distribution

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#297]
## 📋   Anything to add?
IT'S TIME! to publicly announce Giveth TRACE
If no blockers, plan to launch Wednesday July 7, 2021
@ForestSoleil to schedule team launch hack session

## Blockers
- [x] wait for Torus user integration?

## 🎉   Subtasks

- [x] Edit Content on old Medium Posts @laurenluz 
- [x] Publish Launch post on Medium @laurenluz 
- [x] Tweet @laurenluz 
- [x] blast in Giveth @laurenluz 
- [x] Email blast @divine-comedian 
- [ ] Project verification process documentation @WhyldWanderer 
- [x] Share with our donors on Gitcoin @Danibelle @willyogo 
- [x] CS newsletter ?

Blast in Partner Channels:
- [x] Commons Stack MITCH @divine-comedian 
- [x] TEC MITCH @divine-comedian 
- [x] Metagame @laurenluz 
- [x] 1hive - @WhyldWanderer 
- [x] bloom - @WhyldWanderer 
- [x] panvala - @WhyldWanderer 
- [x] dappnode MITCH @divine-comedian 
- [x] gaia gives
- [ ] bright ID @laurenluz 
- [x] WOCA @laurenluz 
- [x] gitcoin  - @WhyldWanderer 
- [x] BoringBananasCo. - @WhyldWanderer 
- [x] MetaCartel DAO - @WhyldWanderer 
- [x] ReSource Network - @WhyldWanderer 
- [x] WalletConnect - @WhyldWanderer
- [x] $WHALE - @WhyldWanderer 
- [x] Aavegotchi - @WhyldWanderer 
- [x] RARA.house - @WhyldWanderer 
- [x] Avastars - @WhyldWanderer 
- [x] Agave - @WhyldWanderer 
- [x] xDai and Friends - @WhyldWanderer 
- [x] sourcecred - @WhyldWanderer 

## References
Launch post: https://docs.google.com/document/d/1eQCh8VQmBHb4BhI3KkCSL3njJh1N2XPJWDgEMXcs_dc/edit

## 🤼‍♂️   Reviewer

@divine-comedian @ForestSoleil @WhyldWanderer @GriffGreen @MoeNick @aminlatifi

**Comment by ForestSoleil** [comment]
Notion notes outlining the Communications Road Map for Giveth TRACE Launch: https://www.notion.so/giveth/Friday-July-2nd-2021-Road-Mapping-715302bae2ec4cfc89b4a53bf9f81e2d

**Comment by ForestSoleil** [comment]
Under sub-tasks, we should add for Mitch to setup link tracking in Amplitude or Google Analytics. And once that's setup, to update the launch post with unique URLs so we can track campaign success. https://github.com/Giveth/giveth-planning/issues/299

**Comment by ForestSoleil** [comment]
Bugs fixed. TRACE devs gave the green light. 
Medium post published. 
Tweet posted. 
@divine-comedian @WhyldWanderer @Danibelle @GriffGreen to share posts today. Please use UTM tracking links and reference this Notion doc when posting: https://www.notion.so/giveth/Comms-TRACE-Launch-Outreach-July-13-2021-88c5cb9310d24e0a86bdcae9dc83d64f

**Comment by laurenluz** [comment]
Wrote a blurb for the CS newsletter and sent it to Kris. I think they will include it for July.

Blurb: https://docs.google.com/document/d/1gwrp_THvTYunz9tmOtj8s9wwlIQFb4vUY0OEc8yLVew/edit
