### ISSUE TITLE
"Meet the Maker" project spotlight calls

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#355]
Set up/organize calls to highlight cool projects on the DApp

**Comment by laurenluz** [comment]
at 1st of the year, expecting to have more engagement in airmeet... this month's is a no-go b/c of giveth vacation

**Comment by laurenluz** [comment]
Next round is 3rd week of december

**Comment by laurenluz** [comment]
could combine with GIVeconomy launch party

**Comment by laurenluz** [comment]
got 8 responses from projects already!

how many do we want? let's revisit next comms call

**Comment by laurenluz** [comment]
7 interested projects - verified projects
Forest to reach out to personal connections w project owners

@WhyldWanderer to add link to form to this issue

**Comment by laurenluz** [comment]
DeSci world is in!

**Comment by WhyldWanderer** [comment]
Typeform for interested projects:

https://giveth.typeform.com/meetthemakers

**Comment by laurenluz** [comment]
@ForestSoleil ^

**Comment by ForestSoleil** [comment]
Reached out to ara from free the food as well as mateo from elev8d red armonia. Waiting to hear back. 

Looks like davids project is not yet verified. I personally would love to do this with teva but we also are not verified so if its only for verified projects we will wait for future rounds.

I am assuming we have dbc, dluz, etc already in the 8 projects? Where is the list of who is already a yes for this?

**Comment by ForestSoleil** [comment]
Have we selected a date for this yet?

**Comment by ForestSoleil** [comment]
Ara is also in. He applied for free the food but in the app had an issue adding his photo in and wants to make sure he can add it in retroactively.

Hes also representing several projects...

Free the food
Recycling
Grey water

And wonders if he can speak to all of them at meet the makers or if we only have space for free the food?

**Comment by ForestSoleil** [comment]
Ashley and I had a call about planning the airmeet event earlier this week.

I am reaching out to all the projects to coordinate a day of event time and a dress rehearsal for the projects physically located here.

I am managing the event itinerary and gathering the necessary info.

Ashley is handling sharing the details with Airmeet and hosting the dress rehearsal at the spaceship.

**Comment by laurenluz** [comment]
Biggest thing we need is to share with audience on Twitter - @WhyldWanderer @ForestSoleil to let @laurenluz know

**Comment by laurenluz** [comment]
What is that date for this?

**Comment by WhyldWanderer** [comment]
We agreed on Feb 4th in the Comms call - @forest is talking with project owners to find out what time of day is best for them

**Comment by laurenluz** [comment]
Feb 4 is the same day as the 1hive Trivia

**Comment by WhyldWanderer** [comment]
Oh sorry.. I got confused.. 
Meet the Makers is Feb 1st
Trivia is Feb 4th

**Comment by ForestSoleil** [comment]
9 projects confirmed for feb 1st meet the makers airmeet 10-1130 am

Created a schedule on the 1st tab here https://docs.google.com/spreadsheets/d/1Fqb0l0g-VMcYCyNYGPb4OsgjTS8teah7Vnf1rBPs6WA/edit#gid=280826157

Asked ann to help with creating promotional tweets to shill this event and hype the projects

I am working on a write up for medium unless we think its best to just shill on twitter and discord

**Comment by laurenluz** [comment]
@WhyldWanderer @ForestSoleil 

I'm not seeing enough clear organization around this in order for it to be a successful event on Tuesday. I think we should make Tuesday's event a "dress rehearsal" before invite any donors, and depending on how that goes, schedule the real event the following week.

This is what I think we need to have in order before anything can happen for real:

- [ ] - The Blog post, shared as a google doc and QA'd be 2 active comms people (standard practice) before publishing
- [ ] - Blog post published 2-4 days before the event
- [ ] - @ForestSoleil if you want to be added as a writer in the Giveth publication you need to make an account and send me your username to add you to it. You would also need to put your post in medium after it is QD's by the team.
- [ ] - Calendar invite created with a clear description of the event and a link to the airmeet
- [ ] - Organization around who is representing "The GIVeconomy"... speakers preppared. I think Ashley would be good at speaking about the GIVbacks program, but you could also ask myself, Griff or Willy... it's not clear to me right now exactly who is supposed to be speaking about what.
- [ ] - The tweet thread with the projects drafted and QA'd, ready to go out 2-4 days before the event
- [ ] - Tweets drafted explaining to donors: the date and time, what to expect, why they should join
- [ ] - Discord shill announcement drafted
- [ ] - Successful access and excecution of the flow in airmeet to test out functionality.

Before the dress rehearsal we should at least have speakers organized and projects organized.

It would also be great to contact some known donors to get them to come if we want this to be particularly impactful, but we can also run it without the additional outreach. However, the above things need to be in place and currently, they aren't.

**Comment by WhyldWanderer** [comment]
I understand what you mean... 
jfyi.. If we do not do it on the 1st, I wont be available to help facilitate this event until Feb 22nd.

**Comment by ForestSoleil** [comment]
Continuing our convo back here from Discord & private pms/calls for transparency...

Hey @laurenluz 
For Medium, here's my account:
@heyforestsoleil
Https://medium.com/@heyforestsoleil

**Comment by ForestSoleil** [comment]
@WhyldWanderer 
Hey love, checking in to see if you ever got access to the airmeet account to test the features?

I'm in the process of rescheduling. Sounds like you will be back for Tues Feb 22nd. I'll make that the first one and we can schedule the next one for Tues March 22nd. Meaning it would be 4th Tuesdays... I wont announce a specific cadence to it but its nice that they are on Month 22nd day, 2022. Flows nicely and I think we will have more than enough interest to do this monthly considering every one of the dozen projects we contacted said yes.

**Comment by WhyldWanderer** [comment]
I do have access now @ForestSoleil

**Comment by laurenluz** [comment]
cool @ForestSoleil if you ever have that blog post QA'd and ready to post ready to publish, I'll add you as a writer.

**Comment by ForestSoleil** [comment]
I organized the schedule for 5 projects around the theme of YOUTH projects for our first event. Here is the Feb 22nd kickoff event post for Medium. I am finishing up this morning before our call. When done I will tag yall for QA. https://docs.google.com/document/d/1Xmn3gxCC4z8QZOA0CDCTeDOY7JpZ29Jv1I4fCpX6qu4/edit?usp=sharing

And also worked on the lineup for the second Meet the Makers on Tuesday, March 22nd. Here is the work in progress draft article for that one.  https://docs.google.com/document/d/120quv9cbQxLR6yNKw7hMVZZJRXdDwUf1EKeQBIFjaVQ/edit?usp=sharing

**Comment by ForestSoleil** [comment]
Kicking off tuesday march 1st!
