### ISSUE TITLE
Video Minicourse - Success stories

### ISSUE THREAD

**Issue by ahmadabugosh** [Giveth/giveth-planning#484]

**Comment by ahmadabugosh** [comment]
This video in the series will show people examples of some successful projects that raised through Giveth, such as: Feed the Hungry in Chilliwack BC, BrightID, DAppNode, template like a project spotlight - highlight different flavours, open to anyone/different types of projects - would be awesome to get people from the projects in it

To Do

- [ ] Create Script

 - [ ] QA/ Review Script
 - [ ] Record Video 
 - [ ]  Edit Video / add closed captions in English
 - [ ]  Upload to video hosting platform
 - [ ]  Promote video

**Comment by Brodyann7** [comment]
potential projects: 

Feed the Hungry in Chilliwack BC - https://giveth.io/project/Feed-the-Hungry-in-Chilliwack-BC-Canada
Free Solidity Development Course in Farsi - https://giveth.io/project/free-solidity-development-course-in-farsi

**Comment by ahmadabugosh** [comment]
I think I would also add  @melodysongq @clara-zi 

- Giveth matching pool https://giveth.io/project/donation-eth
- Unchain https://giveth.io/project/unchain-fund
- Grassroots Economics - Community Currency https://giveth.io/donate/Grassroots-Economics-Community-Currency-0
-  Crypto commons https://giveth.io/project/crypto-commons-gathering-2021
- Gitcoin grants matching pool https://giveth.io/donate/gitcoin-grants-matching-pool

**Comment by laurenluz** [comment]
We discussed converting this into a video series of its own - should we remove from this epic?

**Comment by ahmadabugosh** [comment]
What do you think @melodysongq & @clara-zi ? You mentioned you already started working on this? I think we should convert it into its own project, but I'd be curious to hear your thoughts first

**Comment by clara-zi** [comment]
Yes, please do. I believe this project can then be closed, am I right? Are you ok with that @melodysongq?

**Comment by melodysongq** [comment]
agreed.

**Comment by clara-zi** [comment]
making test success stories vid 'on location' at GRACEAid in London. Now needs editing. @melodysongq @ahmadabugosh

**Comment by clara-zi** [comment]
@ahmadabugosh please pull out the contact emails for these projects?

> potential projects:
> 
> Feed the Hungry in Chilliwack BC - https://giveth.io/project/Feed-the-Hungry-in-Chilliwack-BC-Canada Free Solidity Development Course in Farsi - https://giveth.io/project/free-solidity-development-course-in-farsi

**Comment by laurenluz** [comment]
I will send you their contacts on discord @clara-zi

**Comment by ahmadabugosh** [comment]
Closing since we moved it (and will cover in the project 101 course)
