### ISSUE TITLE
Project Owners 101 Course

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#722]
It would be great to adapt the donors 101 course and offer something to projects.

For starters, some videos we'd need:
- why raise funds in crytpo? where is this going?
- how to create a project
- how to get verified
- what GIVbacks means for your donors
- how to market your project, ways we can support you

Playlist Link: https://www.youtube.com/playlist?list=PL4Artm1rmCWFi-qEkOtjl9nL4tojSIIKm 

Update Nov 1:

**Selected Launch Date: November 8th**

How to announce launch?

- [ ] Blog Post morning of the 8th
- [ ] Announcement Tweet linking to blog post
- [ ] LinkedIn/FB Announcement posts
- [ ] Blurb to post in Discord workshop on the 9th

**Comment by ahmadabugosh** [comment]
Hey @laurenluz we already have an outline here on the "Project Focused" tab (I added all the points you listed): https://docs.google.com/spreadsheets/d/11dtAphLdvv56b4Ko-_PdfcPa9_HGtC8fblJov3Bx1qM/edit#gid=0

What I suggest is for us to agree on the videos (we can discuss it in tomorrow's call), and then I can post them as an epic (like what we did for the donor course) and get started this week!

**Comment by laurenluz** [comment]
oh nice!! sounda great

**Comment by danelsuga** [comment]
@danelsuga tagging myself to stay in the loop!
